#!bin/bash
build() {
echo -ne -n -e "FROM node:14
# Cria um usuário não privilegiado
RUN useradd -m chromium-user
# Instala as dependências do Chromium
RUN apt-get update && apt-get install -y \
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils

# Copia o script e os arquivos necessários
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY index.js .

# Define o usuário não privilegiado como o usuário padrão
USER chromium-user
# Executa o processo do Chromium
CMD [ "npm", "start" ]" > Dockerfile
docker build -t chromium . --network=host
docker run -it --name chromium --network=host chromium
docker start chromium
docker attach chromium
}
build
